import { Farmer } from '../types';

export const mockFarmers: Farmer[] = [
  {
    id: '1',
    first_name: 'Rajesh',
    last_name: 'Kumar',
    name: 'Rajesh Kumar',
    contact: '9876543210',
    gender: 'Male',
    age: 45,
    district: 'Amravati',
    state: 'Maharashtra',
    religion: 'Hindu',
    caste_category: 'OBC',
    marital_status: 'Married',
    land_owned: 4.5,
    crop_types: ['Vegetables', 'Grains'],
    crops: ['Soyabean', 'Cotton'],
    irrigation_facility: true,
    associated_with_fpo: true,
    fpo_name: 'Pyco Farmers Producers Company',
    source: 'WhatsApp Group'
  },
  {
    id: '2',
    first_name: 'Priya',
    last_name: 'Singh',
    name: 'Priya Singh',
    contact: '8765432109',
    gender: 'Female',
    age: 38,
    district: 'Amravati',
    state: 'Maharashtra',
    religion: 'Hindu',
    caste_category: 'General',
    marital_status: 'Married',
    land_owned: 3.2,
    crop_types: ['Fruits', 'Vegetables'],
    crops: ['Oranges', 'Spinach', 'Cauliflower'],
    irrigation_facility: true,
    associated_with_fpo: false,
    source: 'KVK Survey'
  },
  {
    id: '3',
    first_name: 'Mohammed',
    last_name: 'Khan',
    name: 'Mohammed Khan',
    contact: '7654321098',
    gender: 'Male',
    age: 52,
    district: 'Nagpur',
    state: 'Maharashtra',
    religion: 'Muslim',
    caste_category: 'OBC',
    marital_status: 'Married',
    land_owned: 8.0,
    crop_types: ['Cereals', 'Cash Crops'],
    crops: ['Rice', 'Cotton', 'Pulses'],
    irrigation_facility: true,
    associated_with_fpo: true,
    fpo_name: 'Vidarbha Agricultural Producers',
    source: 'Government Survey'
  },
  {
    id: '4',
    first_name: 'Lakshmi',
    last_name: 'Devi',
    name: 'Lakshmi Devi',
    contact: '6543210987',
    gender: 'Female',
    age: 41,
    district: 'Wardha',
    state: 'Maharashtra',
    religion: 'Hindu',
    caste_category: 'SC',
    marital_status: 'Widow',
    land_owned: 2.5,
    crop_types: ['Vegetables'],
    crops: ['Eggplant', 'Okra', 'Chili'],
    irrigation_facility: false,
    associated_with_fpo: true,
    fpo_name: 'Women Farmers Collective',
    source: 'NGO Database'
  },
  {
    id: '5',
    first_name: 'Suresh',
    last_name: 'Sinha',
    name: 'Suresh Sinha',
    contact: '5432109876',
    gender: 'Male',
    age: 60,
    district: 'Nagpur',
    state: 'Maharashtra',
    religion: 'Hindu',
    caste_category: 'General',
    marital_status: 'Married',
    land_owned: 12.0,
    crop_types: ['Fruits', 'Cash Crops'],
    crops: ['Oranges', 'Soybean', 'Cotton'],
    irrigation_facility: true,
    associated_with_fpo: true,
    fpo_name: 'Nagpur Farmers Collective',
    source: 'Agricultural Census'
  },
  {
    id: '6',
    first_name: 'Anita',
    last_name: 'Sharma',
    name: 'Anita Sharma',
    contact: '4321098765',
    gender: 'Female',
    age: 35,
    district: 'Amravati',
    state: 'Maharashtra',
    religion: 'Hindu',
    caste_category: 'OBC',
    marital_status: 'Married',
    land_owned: 4.0,
    crop_types: ['Vegetables', 'Cereals'],
    crops: ['Potatoes', 'Wheat', 'Corn'],
    irrigation_facility: false,
    associated_with_fpo: false,
    source: 'KVK Survey'
  },
  {
    id: '7',
    first_name: 'Harish',
    last_name: 'Joshi',
    name: 'Harish Joshi',
    contact: '3210987654',
    gender: 'Male',
    age: 48,
    district: 'Wardha',
    state: 'Maharashtra',
    religion: 'Hindu',
    caste_category: 'ST',
    marital_status: 'Married',
    land_owned: 6.5,
    crop_types: ['Cereals', 'Fruits'],
    crops: ['Rice', 'Bananas', 'Mangoes'],
    irrigation_facility: true,
    associated_with_fpo: false,
    source: 'Government Survey'
  },
  {
    id: '8',
    first_name: 'Fatima',
    last_name: 'Bano',
    name: 'Fatima Bano',
    contact: '2109876543',
    gender: 'Female',
    age: 42,
    district: 'Nagpur',
    state: 'Maharashtra',
    religion: 'Muslim',
    caste_category: 'OBC',
    marital_status: 'Married',
    land_owned: 5.0,
    crop_types: ['Vegetables', 'Cash Crops'],
    crops: ['Tomatoes', 'Cotton', 'Chili'],
    irrigation_facility: true,
    associated_with_fpo: true,
    fpo_name: 'Vidarbha Agricultural Producers',
    source: 'NGO Database'
  },
  {
    id: '9',
    first_name: 'Ramesh',
    last_name: 'Patil',
    name: 'Ramesh Patil',
    contact: '1098765432',
    gender: 'Male',
    age: 55,
    district: 'Amravati',
    state: 'Maharashtra',
    religion: 'Hindu',
    caste_category: 'SC',
    marital_status: 'Married',
    land_owned: 7.2,
    crop_types: ['Cereals', 'Cash Crops'],
    crops: ['Wheat', 'Soybean', 'Pulses'],
    irrigation_facility: false,
    associated_with_fpo: true,
    fpo_name: 'Amravati Farmers Union',
    source: 'Agricultural Census'
  },
  {
    id: '10',
    first_name: 'Geeta',
    last_name: 'Verma',
    name: 'Geeta Verma',
    contact: '0987654321',
    gender: 'Female',
    age: 36,
    district: 'Nagpur',
    state: 'Maharashtra',
    religion: 'Hindu',
    caste_category: 'General',
    marital_status: 'Unmarried',
    land_owned: 3.0,
    crop_types: ['Fruits', 'Vegetables'],
    crops: ['Oranges', 'Cabbage', 'Carrots'],
    irrigation_facility: true,
    associated_with_fpo: false,
    source: 'KVK Survey'
  },
  {
    id: '11',
    first_name: 'Vijay',
    last_name: 'Thakur',
    name: 'Vijay Thakur',
    contact: '9988776655',
    gender: 'Male',
    age: 50,
    district: 'Chandrapur',
    state: 'Maharashtra',
    religion: 'Hindu',
    caste_category: 'OBC',
    marital_status: 'Married',
    land_owned: 9.5,
    crop_types: ['Cereals', 'Pulses'],
    crops: ['Rice', 'Wheat', 'Lentils'],
    irrigation_facility: true,
    associated_with_fpo: true,
    fpo_name: 'Vidarbha Farmers Association',
    source: 'Government Survey'
  },
  {
    id: '12',
    first_name: 'Sunita',
    last_name: 'Kale',
    name: 'Sunita Kale',
    contact: '8877665544',
    gender: 'Female',
    age: 39,
    district: 'Nagpur',
    state: 'Maharashtra',
    religion: 'Hindu',
    caste_category: 'SC',
    marital_status: 'Married',
    land_owned: 4.2,
    crop_types: ['Vegetables'],
    crops: ['Tomatoes', 'Potatoes', 'Onions'],
    irrigation_facility: false,
    associated_with_fpo: false,
    source: 'NGO Database'
  }
];

export const districts = [...new Set(mockFarmers.map(f => f.district))].sort();
export const states = [...new Set(mockFarmers.map(f => f.state))].sort();
export const religions = [...new Set(mockFarmers.map(f => f.religion))].sort();
export const casteCategories = [...new Set(mockFarmers.map(f => f.caste_category))].sort();
export const maritalStatuses = [...new Set(mockFarmers.map(f => f.marital_status))].sort();
export const cropTypes = [...new Set(mockFarmers.flatMap(f => f.crop_types))].sort();
export const crops = [...new Set(mockFarmers.flatMap(f => f.crops))].sort();
export const fpoNames = [...new Set(mockFarmers.filter(f => f.fpo_name).map(f => f.fpo_name as string))].sort();
export const sources = [...new Set(mockFarmers.map(f => f.source))].sort();

export const filterOptions = {
  demographics: {
    district: districts,
    state: states,
    gender: ['Male', 'Female', 'Other'],
    religion: religions,
    casteCategory: casteCategories,
    maritalStatus: maritalStatuses
  },
  crop_data: {
    cropTypes: cropTypes,
    crops: crops,
    irrigationFacility: [true, false]
  },
  organization: {
    associatedWithFPO: [true, false],
    fpoName: fpoNames.filter(Boolean) as string[]
  },
  source: {
    name: sources
  }
};

export const searchExamples = [
  "Show me all farmers in Nagpur district",
  "Find female farmers who grow fruits",
  "List all farmers with FPO association and irrigation facilities",
  "Show me farmers who own more than 5 acres of land and grow rice",
  "Find Hindu farmers from Amravati who are married"
];
